In [58]:
train_file_path = r"C:\Users\Braja\Desktop\Data Science\ineuron Class\Projects\ML_Project\housing\artifact\data_ingestion\2022-07-08-20-59-35\ingested_data\train\housing.csv"

In [59]:
import pandas as pd

In [60]:
df = pd.read_csv(train_file_path)

In [61]:
df.shape

(16512, 10)

In [62]:
x,y = df.drop(columns=['median_house_value'],axis=1),df[['median_house_value']]

In [63]:
print(x.shape,y.shape)

(16512, 9) (16512, 1)


In [64]:
x.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        158
population              0
households              0
median_income           0
ocean_proximity         0
dtype: int64

In [65]:
from sklearn.impute import SimpleImputer

In [66]:
x.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income ocean_proximity  
0      2237.0       706.0         2.1736          INLAND  
1      2015.0       768.0         6.3373      NEAR OCEAN  
2       667.0       300.0         2.8750          INLAND  
3       898.0       483.0         2.2264      NEAR OCEAN  
4      1837.0       580.0         4.4964       <1H OCEAN

In [67]:
nummerical_column = x.drop(columns=['ocean_proximity'],axis=1)

In [68]:
nummerical_column.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -121.46     38.52                29.0       3873.0           797.0   
1    -117.23     33.09                 7.0       5320.0           855.0   
2    -119.04     35.37                44.0       1618.0           310.0   
3    -117.13     32.75                24.0       1877.0           519.0   
4    -118.70     34.28                27.0       3536.0           646.0   

   population  households  median_income  
0      2237.0       706.0         2.1736  
1      2015.0       768.0         6.3373  
2       667.0       300.0         2.8750  
3       898.0       483.0         2.2264  
4      1837.0       580.0         4.4964

In [69]:
simple_imputer = SimpleImputer(strategy='median')

In [70]:
simple_imputer.fit_transform(nummerical_column)

array([[-1.2146e+02,  3.8520e+01,  2.9000e+01, ...,  2.2370e+03,
         7.0600e+02,  2.1736e+00],
       [-1.1723e+02,  3.3090e+01,  7.0000e+00, ...,  2.0150e+03,
         7.6800e+02,  6.3373e+00],
       [-1.1904e+02,  3.5370e+01,  4.4000e+01, ...,  6.6700e+02,
         3.0000e+02,  2.8750e+00],
       ...,
       [-1.2272e+02,  3.8440e+01,  4.8000e+01, ...,  4.5800e+02,
         1.7200e+02,  3.1797e+00],
       [-1.2270e+02,  3.8310e+01,  1.4000e+01, ...,  1.2080e+03,
         5.0100e+02,  4.1964e+00],
       [-1.2214e+02,  3.9970e+01,  2.7000e+01, ...,  6.2500e+02,
         1.9700e+02,  3.1319e+00]])

In [71]:
df = simple_imputer.transform(nummerical_column)

In [72]:
simple_imputer.feature_names_in_

array(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income'],
      dtype=object)

In [73]:
simple_imputer.statistics_

array([-118.51   ,   34.26   ,   29.     , 2119.     ,  433.     ,
       1164.     ,  408.     ,    3.54155])

In [74]:
x.ocean_proximity.value_counts()

<1H OCEAN     7277
INLAND        5262
NEAR OCEAN    2124
NEAR BAY      1847
ISLAND           2
Name: ocean_proximity, dtype: int64

In [75]:
from sklearn.base import BaseEstimator,TransformerMixin

In [76]:
class test(BaseEstimator,TransformerMixin):

    def __init__(self,strategy="median"):
        self.strategy = strategy

    def fit(self,x):
        self.features_ = x.columns
        self.statistics_ = []
        for column in x.columns:
            self.statistics_.append(x[column].median())

        return self
    def trasform(self,x:pd.DataFrame):
        for idx,column in enumerate(x.columns):
            x[column].fillna(self.statistics_[idx])
        return x

    #def fit_trasform(self,x):
    #    self.fit(x)
    #    self.trasform(x)
    


In [77]:
test().fit(nummerical_column).statistics_

[-118.51, 34.26, 29.0, 2119.0, 433.0, 1164.0, 408.0, 3.54155]

In [78]:
x.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [79]:
import numpy as np

In [80]:
COLUMN_TOTAL_ROOMS = "total_rooms"
COLUMN_POPULATION = "population"
COLUMN_HOUSEHOLDS = "households"
COLUMN_TOTAL_BEDROOM = "total_bedrooms"

class featureGenerator(BaseEstimator,TransformerMixin):

    def __init__(self, add_bedrooms_per_room = True,
                total_rooms_ix = 3,
                population_ix = 5,
                households_ix = 6,
                total_bedrooms_ix = 4, columns = None):
        """
        FeatureGenerator Initialization
        add_bedrooms_per_room: bool
        total_rooms_ix: int index number of total rooms columns
        population_ix: int index number of total population columns
        households_ix: int index number of households columns
        total_bedrooms_ix: int index number of total bedrooms columns
        """
        try:
            self.columns = columns
            if self.columns is not None:
                total_rooms_ix = self.columns.index(COLUMN_TOTAL_ROOMS)
                population_ix = self.columns.index(COLUMN_POPULATION)
                households_ix = self.columns.index(COLUMN_HOUSEHOLDS)
                total_bedrooms_ix = self.columns.index(COLUMN_TOTAL_BEDROOM)

            self.add_bedrooms_per_room = add_bedrooms_per_room
            self.total_rooms_ix = total_rooms_ix
            self.population_ix = population_ix
            self.households_ix = households_ix
            self.total_bedrooms_ix = total_bedrooms_ix
            
        except Exception as e:
            raise e

    def fit(self,x,y=None):
        return self

    def transform(self,x,y=None):
        try:
            room_per_household = x[:, self.total_rooms_ix] / \
                                x[:,self.households_ix]
            population_per_household = x[:, self.population_ix] / \
                                        x[:, self.households_ix]
            if self.add_bedrooms_per_room:
                bedroom_per_room = x[:, self.total_bedrooms_ix] / \
                                    x[:,self.total_rooms_ix]
                generated_feature = np.c_[
                    x, room_per_household, population_per_household, bedroom_per_room]
            else:
                generated_feature = np.c_[
                    x, room_per_household, population_per_household]
            return generated_feature
        except Exception as e:
            raise e

In [81]:
arr1 = np.arange(10)
arr2 = np.arange(10)

In [82]:
np.c_[arr1,arr2]

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [83]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [84]:
num_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="median")),
    ('feature_generator',featureGenerator()),
    ('scaling',StandardScaler())
])

In [85]:
num_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('feature_generator', featureGenerator()),
                ('scaling', StandardScaler())])

In [86]:
from sklearn.preprocessing import OneHotEncoder

In [87]:
cat_pipeline = Pipeline(steps = [
    ('imputer',SimpleImputer(strategy="most_frequent")),
    ('OneHotEncoder',OneHotEncoder()),
    ('scaling',StandardScaler(with_mean=False))
])

In [88]:
cat_pipeline

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('OneHotEncoder', OneHotEncoder()),
                ('scaling', StandardScaler(with_mean=False))])

In [89]:
df = pd.read_csv(train_file_path)

In [90]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'ocean_proximity'],
      dtype='object')

In [91]:
num_column_name = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']
cat_column_name = ['ocean_proximity']

In [92]:
preprocessing = ColumnTransformer([
    ('num_pipelie',num_pipeline,num_column_name),
    ('cat_pipeline',cat_pipeline,cat_column_name)
])

In [93]:
preprocessing.fit_transform(df)

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.        ,
         0.        ,  2.9869105 ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ...,  0.        ,
         0.        ,  0.        ],
       [-1.56080303,  1.2492109 , -1.1653327 , ...,  0.        ,
         0.        ,  0.        ],
       [-1.28105026,  2.02567448, -0.13148926, ...,  0.        ,
         0.        ,  0.        ]])

In [94]:
test_df = pd.read_csv(r'C:\Users\Braja\Desktop\Data Science\ineuron Class\Projects\ML_Project\housing\artifact\data_ingestion\2022-07-08-20-59-35\ingested_data\test\housing.csv')

In [95]:
preprocessing.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])

In [96]:
import dill

In [97]:
with open('preprocessing.pkl',"wb") as prep_file:
    dill.dump(preprocessing,prep_file)

In [98]:
with open('preprocessing.pkl',"rb") as prep_file:
    prep_loaded_obj = dill.load(prep_file)

In [99]:
prep_loaded_obj.transform(test_df)

array([[ 0.59229422, -0.71065803,  0.02756357, ...,  0.        ,
         0.        ,  0.        ],
       [-0.42180959, -0.35049119, -0.37006852, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.56232071, -0.64985064,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.07211862, -0.56097831,  1.14093342, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.83208232, -0.93985512,  0.10708999, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.50736927, -0.67791559,  0.5842485 , ...,  0.        ,
         0.        ,  0.        ]])